package com.cn.lucky.morning.model.dao;

import com.cn.lucky.morning.model.domain.BookSource;
import com.cn.lucky.morning.model.domain.BookSourceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BookSourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_book_source
     *
     * @mbg.generated
     */
    long countByExample(BookSourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_book_source
     *
     * @mbg.generated
     */
    int deleteByExample(BookSourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_book_source
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_book_source
     *
     * @mbg.generated
     */
    int insert(BookSource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_book_source
     *
     * @mbg.generated
     */
    int insertSelective(BookSource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_book_source
     *
     * @mbg.generated
     */
    List<BookSource> selectByExample(BookSourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_book_source
     *
     * @mbg.generated
     */
    BookSource selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_book_source
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") BookSource record, @Param("example") BookSourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_book_source
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") BookSource record, @Param("example") BookSourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_book_source
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BookSource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_book_source
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BookSource record);
}