package com.cn.lucky.morning.model.dao;

import com.cn.lucky.morning.model.domain.BookInfo;
import com.cn.lucky.morning.model.domain.BookInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BookInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_book_info
     *
     * @mbg.generated
     */
    long countByExample(BookInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_book_info
     *
     * @mbg.generated
     */
    int deleteByExample(BookInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_book_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_book_info
     *
     * @mbg.generated
     */
    int insert(BookInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_book_info
     *
     * @mbg.generated
     */
    int insertSelective(BookInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_book_info
     *
     * @mbg.generated
     */
    List<BookInfo> selectByExample(BookInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_book_info
     *
     * @mbg.generated
     */
    BookInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_book_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") BookInfo record, @Param("example") BookInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_book_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") BookInfo record, @Param("example") BookInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_book_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BookInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_book_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BookInfo record);
}