package com.cn.lucky.morning.model.dao;

import com.cn.lucky.morning.model.domain.Donate;
import com.cn.lucky.morning.model.domain.DonateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DonateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_donate
     *
     * @mbg.generated
     */
    long countByExample(DonateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_donate
     *
     * @mbg.generated
     */
    int deleteByExample(DonateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_donate
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_donate
     *
     * @mbg.generated
     */
    int insert(Donate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_donate
     *
     * @mbg.generated
     */
    int insertSelective(Donate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_donate
     *
     * @mbg.generated
     */
    List<Donate> selectByExample(DonateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_donate
     *
     * @mbg.generated
     */
    Donate selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_donate
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Donate record, @Param("example") DonateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_donate
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Donate record, @Param("example") DonateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_donate
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Donate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_donate
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Donate record);
}