package com.cn.lucky.morning.model.dao;

import com.cn.lucky.morning.model.domain.SystemSetting;
import com.cn.lucky.morning.model.domain.SystemSettingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SystemSettingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_system_setting
     *
     * @mbg.generated
     */
    long countByExample(SystemSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_system_setting
     *
     * @mbg.generated
     */
    int deleteByExample(SystemSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_system_setting
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_system_setting
     *
     * @mbg.generated
     */
    int insert(SystemSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_system_setting
     *
     * @mbg.generated
     */
    int insertSelective(SystemSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_system_setting
     *
     * @mbg.generated
     */
    List<SystemSetting> selectByExample(SystemSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_system_setting
     *
     * @mbg.generated
     */
    SystemSetting selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_system_setting
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SystemSetting record, @Param("example") SystemSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_system_setting
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SystemSetting record, @Param("example") SystemSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_system_setting
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SystemSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_system_setting
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SystemSetting record);
}