package com.cn.lucky.morning.model.dao;

import com.cn.lucky.morning.model.domain.SystemNotification;
import com.cn.lucky.morning.model.domain.SystemNotificationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SystemNotificationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_system_notification
     *
     * @mbg.generated
     */
    long countByExample(SystemNotificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_system_notification
     *
     * @mbg.generated
     */
    int deleteByExample(SystemNotificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_system_notification
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_system_notification
     *
     * @mbg.generated
     */
    int insert(SystemNotification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_system_notification
     *
     * @mbg.generated
     */
    int insertSelective(SystemNotification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_system_notification
     *
     * @mbg.generated
     */
    List<SystemNotification> selectByExample(SystemNotificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_system_notification
     *
     * @mbg.generated
     */
    SystemNotification selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_system_notification
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SystemNotification record, @Param("example") SystemNotificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_system_notification
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SystemNotification record, @Param("example") SystemNotificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_system_notification
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SystemNotification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_system_notification
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SystemNotification record);
}