package com.cn.lucky.morning.model.dao;

import com.cn.lucky.morning.model.domain.UpdateLog;
import com.cn.lucky.morning.model.domain.UpdateLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UpdateLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_update_log
     *
     * @mbg.generated
     */
    long countByExample(UpdateLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_update_log
     *
     * @mbg.generated
     */
    int deleteByExample(UpdateLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_update_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_update_log
     *
     * @mbg.generated
     */
    int insert(UpdateLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_update_log
     *
     * @mbg.generated
     */
    int insertSelective(UpdateLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_update_log
     *
     * @mbg.generated
     */
    List<UpdateLog> selectByExampleWithBLOBs(UpdateLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_update_log
     *
     * @mbg.generated
     */
    List<UpdateLog> selectByExample(UpdateLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_update_log
     *
     * @mbg.generated
     */
    UpdateLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_update_log
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") UpdateLog record, @Param("example") UpdateLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_update_log
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") UpdateLog record, @Param("example") UpdateLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_update_log
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") UpdateLog record, @Param("example") UpdateLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_update_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UpdateLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_update_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(UpdateLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_update_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UpdateLog record);
}