package com.cn.lucky.morning.model.domain;

import java.sql.Timestamp;

public class AuthorityGroup {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_authority_group.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_authority_group.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_authority_group.created
     *
     * @mbg.generated
     */
    private Timestamp created;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_authority_group.updated
     *
     * @mbg.generated
     */
    private Timestamp updated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_authority_group.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_authority_group.id
     *
     * @return the value of m_authority_group.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_authority_group.id
     *
     * @param id the value for m_authority_group.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_authority_group.name
     *
     * @return the value of m_authority_group.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_authority_group.name
     *
     * @param name the value for m_authority_group.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_authority_group.created
     *
     * @return the value of m_authority_group.created
     *
     * @mbg.generated
     */
    public Timestamp getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_authority_group.created
     *
     * @param created the value for m_authority_group.created
     *
     * @mbg.generated
     */
    public void setCreated(Timestamp created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_authority_group.updated
     *
     * @return the value of m_authority_group.updated
     *
     * @mbg.generated
     */
    public Timestamp getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_authority_group.updated
     *
     * @param updated the value for m_authority_group.updated
     *
     * @mbg.generated
     */
    public void setUpdated(Timestamp updated) {
        this.updated = updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_authority_group.description
     *
     * @return the value of m_authority_group.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_authority_group.description
     *
     * @param description the value for m_authority_group.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}