package com.cn.lucky.morning.model.domain;

import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.List;

public class BookInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table m_book_info
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table m_book_info
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table m_book_info
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table m_book_info
     *
     * @mbg.generated
     */
    protected int limitStart = -1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table m_book_info
     *
     * @mbg.generated
     */
    protected int limitEnd = -1;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_book_info
     *
     * @mbg.generated
     */
    public BookInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_book_info
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_book_info
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_book_info
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_book_info
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_book_info
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_book_info
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_book_info
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_book_info
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_book_info
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_book_info
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_book_info
     *
     * @mbg.generated
     */
    public void setLimitStart(int limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_book_info
     *
     * @mbg.generated
     */
    public int getLimitStart() {
        return limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_book_info
     *
     * @mbg.generated
     */
    public void setLimitEnd(int limitEnd) {
        this.limitEnd=limitEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_book_info
     *
     * @mbg.generated
     */
    public int getLimitEnd() {
        return limitEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_book_info
     *
     * @mbg.generated
     */
    public void setPage(int page, int size) {
        this.limitStart = page * size;this.limitEnd = size;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table m_book_info
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andBookUrlIsNull() {
            addCriterion("book_url is null");
            return (Criteria) this;
        }

        public Criteria andBookUrlIsNotNull() {
            addCriterion("book_url is not null");
            return (Criteria) this;
        }

        public Criteria andBookUrlEqualTo(String value) {
            addCriterion("book_url =", value, "bookUrl");
            return (Criteria) this;
        }

        public Criteria andBookUrlNotEqualTo(String value) {
            addCriterion("book_url <>", value, "bookUrl");
            return (Criteria) this;
        }

        public Criteria andBookUrlGreaterThan(String value) {
            addCriterion("book_url >", value, "bookUrl");
            return (Criteria) this;
        }

        public Criteria andBookUrlGreaterThanOrEqualTo(String value) {
            addCriterion("book_url >=", value, "bookUrl");
            return (Criteria) this;
        }

        public Criteria andBookUrlLessThan(String value) {
            addCriterion("book_url <", value, "bookUrl");
            return (Criteria) this;
        }

        public Criteria andBookUrlLessThanOrEqualTo(String value) {
            addCriterion("book_url <=", value, "bookUrl");
            return (Criteria) this;
        }

        public Criteria andBookUrlLike(String value) {
            addCriterion("book_url like", value, "bookUrl");
            return (Criteria) this;
        }

        public Criteria andBookUrlNotLike(String value) {
            addCriterion("book_url not like", value, "bookUrl");
            return (Criteria) this;
        }

        public Criteria andBookUrlIn(List<String> values) {
            addCriterion("book_url in", values, "bookUrl");
            return (Criteria) this;
        }

        public Criteria andBookUrlNotIn(List<String> values) {
            addCriterion("book_url not in", values, "bookUrl");
            return (Criteria) this;
        }

        public Criteria andBookUrlBetween(String value1, String value2) {
            addCriterion("book_url between", value1, value2, "bookUrl");
            return (Criteria) this;
        }

        public Criteria andBookUrlNotBetween(String value1, String value2) {
            addCriterion("book_url not between", value1, value2, "bookUrl");
            return (Criteria) this;
        }

        public Criteria andBookSourceLinkIsNull() {
            addCriterion("book_source_link is null");
            return (Criteria) this;
        }

        public Criteria andBookSourceLinkIsNotNull() {
            addCriterion("book_source_link is not null");
            return (Criteria) this;
        }

        public Criteria andBookSourceLinkEqualTo(String value) {
            addCriterion("book_source_link =", value, "bookSourceLink");
            return (Criteria) this;
        }

        public Criteria andBookSourceLinkNotEqualTo(String value) {
            addCriterion("book_source_link <>", value, "bookSourceLink");
            return (Criteria) this;
        }

        public Criteria andBookSourceLinkGreaterThan(String value) {
            addCriterion("book_source_link >", value, "bookSourceLink");
            return (Criteria) this;
        }

        public Criteria andBookSourceLinkGreaterThanOrEqualTo(String value) {
            addCriterion("book_source_link >=", value, "bookSourceLink");
            return (Criteria) this;
        }

        public Criteria andBookSourceLinkLessThan(String value) {
            addCriterion("book_source_link <", value, "bookSourceLink");
            return (Criteria) this;
        }

        public Criteria andBookSourceLinkLessThanOrEqualTo(String value) {
            addCriterion("book_source_link <=", value, "bookSourceLink");
            return (Criteria) this;
        }

        public Criteria andBookSourceLinkLike(String value) {
            addCriterion("book_source_link like", value, "bookSourceLink");
            return (Criteria) this;
        }

        public Criteria andBookSourceLinkNotLike(String value) {
            addCriterion("book_source_link not like", value, "bookSourceLink");
            return (Criteria) this;
        }

        public Criteria andBookSourceLinkIn(List<String> values) {
            addCriterion("book_source_link in", values, "bookSourceLink");
            return (Criteria) this;
        }

        public Criteria andBookSourceLinkNotIn(List<String> values) {
            addCriterion("book_source_link not in", values, "bookSourceLink");
            return (Criteria) this;
        }

        public Criteria andBookSourceLinkBetween(String value1, String value2) {
            addCriterion("book_source_link between", value1, value2, "bookSourceLink");
            return (Criteria) this;
        }

        public Criteria andBookSourceLinkNotBetween(String value1, String value2) {
            addCriterion("book_source_link not between", value1, value2, "bookSourceLink");
            return (Criteria) this;
        }

        public Criteria andBookSourceNameIsNull() {
            addCriterion("book_source_name is null");
            return (Criteria) this;
        }

        public Criteria andBookSourceNameIsNotNull() {
            addCriterion("book_source_name is not null");
            return (Criteria) this;
        }

        public Criteria andBookSourceNameEqualTo(String value) {
            addCriterion("book_source_name =", value, "bookSourceName");
            return (Criteria) this;
        }

        public Criteria andBookSourceNameNotEqualTo(String value) {
            addCriterion("book_source_name <>", value, "bookSourceName");
            return (Criteria) this;
        }

        public Criteria andBookSourceNameGreaterThan(String value) {
            addCriterion("book_source_name >", value, "bookSourceName");
            return (Criteria) this;
        }

        public Criteria andBookSourceNameGreaterThanOrEqualTo(String value) {
            addCriterion("book_source_name >=", value, "bookSourceName");
            return (Criteria) this;
        }

        public Criteria andBookSourceNameLessThan(String value) {
            addCriterion("book_source_name <", value, "bookSourceName");
            return (Criteria) this;
        }

        public Criteria andBookSourceNameLessThanOrEqualTo(String value) {
            addCriterion("book_source_name <=", value, "bookSourceName");
            return (Criteria) this;
        }

        public Criteria andBookSourceNameLike(String value) {
            addCriterion("book_source_name like", value, "bookSourceName");
            return (Criteria) this;
        }

        public Criteria andBookSourceNameNotLike(String value) {
            addCriterion("book_source_name not like", value, "bookSourceName");
            return (Criteria) this;
        }

        public Criteria andBookSourceNameIn(List<String> values) {
            addCriterion("book_source_name in", values, "bookSourceName");
            return (Criteria) this;
        }

        public Criteria andBookSourceNameNotIn(List<String> values) {
            addCriterion("book_source_name not in", values, "bookSourceName");
            return (Criteria) this;
        }

        public Criteria andBookSourceNameBetween(String value1, String value2) {
            addCriterion("book_source_name between", value1, value2, "bookSourceName");
            return (Criteria) this;
        }

        public Criteria andBookSourceNameNotBetween(String value1, String value2) {
            addCriterion("book_source_name not between", value1, value2, "bookSourceName");
            return (Criteria) this;
        }

        public Criteria andBookImgIsNull() {
            addCriterion("book_img is null");
            return (Criteria) this;
        }

        public Criteria andBookImgIsNotNull() {
            addCriterion("book_img is not null");
            return (Criteria) this;
        }

        public Criteria andBookImgEqualTo(String value) {
            addCriterion("book_img =", value, "bookImg");
            return (Criteria) this;
        }

        public Criteria andBookImgNotEqualTo(String value) {
            addCriterion("book_img <>", value, "bookImg");
            return (Criteria) this;
        }

        public Criteria andBookImgGreaterThan(String value) {
            addCriterion("book_img >", value, "bookImg");
            return (Criteria) this;
        }

        public Criteria andBookImgGreaterThanOrEqualTo(String value) {
            addCriterion("book_img >=", value, "bookImg");
            return (Criteria) this;
        }

        public Criteria andBookImgLessThan(String value) {
            addCriterion("book_img <", value, "bookImg");
            return (Criteria) this;
        }

        public Criteria andBookImgLessThanOrEqualTo(String value) {
            addCriterion("book_img <=", value, "bookImg");
            return (Criteria) this;
        }

        public Criteria andBookImgLike(String value) {
            addCriterion("book_img like", value, "bookImg");
            return (Criteria) this;
        }

        public Criteria andBookImgNotLike(String value) {
            addCriterion("book_img not like", value, "bookImg");
            return (Criteria) this;
        }

        public Criteria andBookImgIn(List<String> values) {
            addCriterion("book_img in", values, "bookImg");
            return (Criteria) this;
        }

        public Criteria andBookImgNotIn(List<String> values) {
            addCriterion("book_img not in", values, "bookImg");
            return (Criteria) this;
        }

        public Criteria andBookImgBetween(String value1, String value2) {
            addCriterion("book_img between", value1, value2, "bookImg");
            return (Criteria) this;
        }

        public Criteria andBookImgNotBetween(String value1, String value2) {
            addCriterion("book_img not between", value1, value2, "bookImg");
            return (Criteria) this;
        }

        public Criteria andBookImgErrorIsNull() {
            addCriterion("book_img_error is null");
            return (Criteria) this;
        }

        public Criteria andBookImgErrorIsNotNull() {
            addCriterion("book_img_error is not null");
            return (Criteria) this;
        }

        public Criteria andBookImgErrorEqualTo(String value) {
            addCriterion("book_img_error =", value, "bookImgError");
            return (Criteria) this;
        }

        public Criteria andBookImgErrorNotEqualTo(String value) {
            addCriterion("book_img_error <>", value, "bookImgError");
            return (Criteria) this;
        }

        public Criteria andBookImgErrorGreaterThan(String value) {
            addCriterion("book_img_error >", value, "bookImgError");
            return (Criteria) this;
        }

        public Criteria andBookImgErrorGreaterThanOrEqualTo(String value) {
            addCriterion("book_img_error >=", value, "bookImgError");
            return (Criteria) this;
        }

        public Criteria andBookImgErrorLessThan(String value) {
            addCriterion("book_img_error <", value, "bookImgError");
            return (Criteria) this;
        }

        public Criteria andBookImgErrorLessThanOrEqualTo(String value) {
            addCriterion("book_img_error <=", value, "bookImgError");
            return (Criteria) this;
        }

        public Criteria andBookImgErrorLike(String value) {
            addCriterion("book_img_error like", value, "bookImgError");
            return (Criteria) this;
        }

        public Criteria andBookImgErrorNotLike(String value) {
            addCriterion("book_img_error not like", value, "bookImgError");
            return (Criteria) this;
        }

        public Criteria andBookImgErrorIn(List<String> values) {
            addCriterion("book_img_error in", values, "bookImgError");
            return (Criteria) this;
        }

        public Criteria andBookImgErrorNotIn(List<String> values) {
            addCriterion("book_img_error not in", values, "bookImgError");
            return (Criteria) this;
        }

        public Criteria andBookImgErrorBetween(String value1, String value2) {
            addCriterion("book_img_error between", value1, value2, "bookImgError");
            return (Criteria) this;
        }

        public Criteria andBookImgErrorNotBetween(String value1, String value2) {
            addCriterion("book_img_error not between", value1, value2, "bookImgError");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andAuthorIsNull() {
            addCriterion("author is null");
            return (Criteria) this;
        }

        public Criteria andAuthorIsNotNull() {
            addCriterion("author is not null");
            return (Criteria) this;
        }

        public Criteria andAuthorEqualTo(String value) {
            addCriterion("author =", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorNotEqualTo(String value) {
            addCriterion("author <>", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorGreaterThan(String value) {
            addCriterion("author >", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorGreaterThanOrEqualTo(String value) {
            addCriterion("author >=", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorLessThan(String value) {
            addCriterion("author <", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorLessThanOrEqualTo(String value) {
            addCriterion("author <=", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorLike(String value) {
            addCriterion("author like", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorNotLike(String value) {
            addCriterion("author not like", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorIn(List<String> values) {
            addCriterion("author in", values, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorNotIn(List<String> values) {
            addCriterion("author not in", values, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorBetween(String value1, String value2) {
            addCriterion("author between", value1, value2, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorNotBetween(String value1, String value2) {
            addCriterion("author not between", value1, value2, "author");
            return (Criteria) this;
        }

        public Criteria andNovelDesIsNull() {
            addCriterion("novel_des is null");
            return (Criteria) this;
        }

        public Criteria andNovelDesIsNotNull() {
            addCriterion("novel_des is not null");
            return (Criteria) this;
        }

        public Criteria andNovelDesEqualTo(String value) {
            addCriterion("novel_des =", value, "novelDes");
            return (Criteria) this;
        }

        public Criteria andNovelDesNotEqualTo(String value) {
            addCriterion("novel_des <>", value, "novelDes");
            return (Criteria) this;
        }

        public Criteria andNovelDesGreaterThan(String value) {
            addCriterion("novel_des >", value, "novelDes");
            return (Criteria) this;
        }

        public Criteria andNovelDesGreaterThanOrEqualTo(String value) {
            addCriterion("novel_des >=", value, "novelDes");
            return (Criteria) this;
        }

        public Criteria andNovelDesLessThan(String value) {
            addCriterion("novel_des <", value, "novelDes");
            return (Criteria) this;
        }

        public Criteria andNovelDesLessThanOrEqualTo(String value) {
            addCriterion("novel_des <=", value, "novelDes");
            return (Criteria) this;
        }

        public Criteria andNovelDesLike(String value) {
            addCriterion("novel_des like", value, "novelDes");
            return (Criteria) this;
        }

        public Criteria andNovelDesNotLike(String value) {
            addCriterion("novel_des not like", value, "novelDes");
            return (Criteria) this;
        }

        public Criteria andNovelDesIn(List<String> values) {
            addCriterion("novel_des in", values, "novelDes");
            return (Criteria) this;
        }

        public Criteria andNovelDesNotIn(List<String> values) {
            addCriterion("novel_des not in", values, "novelDes");
            return (Criteria) this;
        }

        public Criteria andNovelDesBetween(String value1, String value2) {
            addCriterion("novel_des between", value1, value2, "novelDes");
            return (Criteria) this;
        }

        public Criteria andNovelDesNotBetween(String value1, String value2) {
            addCriterion("novel_des not between", value1, value2, "novelDes");
            return (Criteria) this;
        }

        public Criteria andNovelTypeIsNull() {
            addCriterion("novel_type is null");
            return (Criteria) this;
        }

        public Criteria andNovelTypeIsNotNull() {
            addCriterion("novel_type is not null");
            return (Criteria) this;
        }

        public Criteria andNovelTypeEqualTo(String value) {
            addCriterion("novel_type =", value, "novelType");
            return (Criteria) this;
        }

        public Criteria andNovelTypeNotEqualTo(String value) {
            addCriterion("novel_type <>", value, "novelType");
            return (Criteria) this;
        }

        public Criteria andNovelTypeGreaterThan(String value) {
            addCriterion("novel_type >", value, "novelType");
            return (Criteria) this;
        }

        public Criteria andNovelTypeGreaterThanOrEqualTo(String value) {
            addCriterion("novel_type >=", value, "novelType");
            return (Criteria) this;
        }

        public Criteria andNovelTypeLessThan(String value) {
            addCriterion("novel_type <", value, "novelType");
            return (Criteria) this;
        }

        public Criteria andNovelTypeLessThanOrEqualTo(String value) {
            addCriterion("novel_type <=", value, "novelType");
            return (Criteria) this;
        }

        public Criteria andNovelTypeLike(String value) {
            addCriterion("novel_type like", value, "novelType");
            return (Criteria) this;
        }

        public Criteria andNovelTypeNotLike(String value) {
            addCriterion("novel_type not like", value, "novelType");
            return (Criteria) this;
        }

        public Criteria andNovelTypeIn(List<String> values) {
            addCriterion("novel_type in", values, "novelType");
            return (Criteria) this;
        }

        public Criteria andNovelTypeNotIn(List<String> values) {
            addCriterion("novel_type not in", values, "novelType");
            return (Criteria) this;
        }

        public Criteria andNovelTypeBetween(String value1, String value2) {
            addCriterion("novel_type between", value1, value2, "novelType");
            return (Criteria) this;
        }

        public Criteria andNovelTypeNotBetween(String value1, String value2) {
            addCriterion("novel_type not between", value1, value2, "novelType");
            return (Criteria) this;
        }

        public Criteria andLastUpdateIsNull() {
            addCriterion("last_update is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateIsNotNull() {
            addCriterion("last_update is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateEqualTo(String value) {
            addCriterion("last_update =", value, "lastUpdate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateNotEqualTo(String value) {
            addCriterion("last_update <>", value, "lastUpdate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateGreaterThan(String value) {
            addCriterion("last_update >", value, "lastUpdate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateGreaterThanOrEqualTo(String value) {
            addCriterion("last_update >=", value, "lastUpdate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateLessThan(String value) {
            addCriterion("last_update <", value, "lastUpdate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateLessThanOrEqualTo(String value) {
            addCriterion("last_update <=", value, "lastUpdate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateLike(String value) {
            addCriterion("last_update like", value, "lastUpdate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateNotLike(String value) {
            addCriterion("last_update not like", value, "lastUpdate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateIn(List<String> values) {
            addCriterion("last_update in", values, "lastUpdate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateNotIn(List<String> values) {
            addCriterion("last_update not in", values, "lastUpdate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateBetween(String value1, String value2) {
            addCriterion("last_update between", value1, value2, "lastUpdate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateNotBetween(String value1, String value2) {
            addCriterion("last_update not between", value1, value2, "lastUpdate");
            return (Criteria) this;
        }

        public Criteria andLastNewIsNull() {
            addCriterion("last_new is null");
            return (Criteria) this;
        }

        public Criteria andLastNewIsNotNull() {
            addCriterion("last_new is not null");
            return (Criteria) this;
        }

        public Criteria andLastNewEqualTo(String value) {
            addCriterion("last_new =", value, "lastNew");
            return (Criteria) this;
        }

        public Criteria andLastNewNotEqualTo(String value) {
            addCriterion("last_new <>", value, "lastNew");
            return (Criteria) this;
        }

        public Criteria andLastNewGreaterThan(String value) {
            addCriterion("last_new >", value, "lastNew");
            return (Criteria) this;
        }

        public Criteria andLastNewGreaterThanOrEqualTo(String value) {
            addCriterion("last_new >=", value, "lastNew");
            return (Criteria) this;
        }

        public Criteria andLastNewLessThan(String value) {
            addCriterion("last_new <", value, "lastNew");
            return (Criteria) this;
        }

        public Criteria andLastNewLessThanOrEqualTo(String value) {
            addCriterion("last_new <=", value, "lastNew");
            return (Criteria) this;
        }

        public Criteria andLastNewLike(String value) {
            addCriterion("last_new like", value, "lastNew");
            return (Criteria) this;
        }

        public Criteria andLastNewNotLike(String value) {
            addCriterion("last_new not like", value, "lastNew");
            return (Criteria) this;
        }

        public Criteria andLastNewIn(List<String> values) {
            addCriterion("last_new in", values, "lastNew");
            return (Criteria) this;
        }

        public Criteria andLastNewNotIn(List<String> values) {
            addCriterion("last_new not in", values, "lastNew");
            return (Criteria) this;
        }

        public Criteria andLastNewBetween(String value1, String value2) {
            addCriterion("last_new between", value1, value2, "lastNew");
            return (Criteria) this;
        }

        public Criteria andLastNewNotBetween(String value1, String value2) {
            addCriterion("last_new not between", value1, value2, "lastNew");
            return (Criteria) this;
        }

        public Criteria andCreatorIdIsNull() {
            addCriterion("creator_id is null");
            return (Criteria) this;
        }

        public Criteria andCreatorIdIsNotNull() {
            addCriterion("creator_id is not null");
            return (Criteria) this;
        }

        public Criteria andCreatorIdEqualTo(Long value) {
            addCriterion("creator_id =", value, "creatorId");
            return (Criteria) this;
        }

        public Criteria andCreatorIdNotEqualTo(Long value) {
            addCriterion("creator_id <>", value, "creatorId");
            return (Criteria) this;
        }

        public Criteria andCreatorIdGreaterThan(Long value) {
            addCriterion("creator_id >", value, "creatorId");
            return (Criteria) this;
        }

        public Criteria andCreatorIdGreaterThanOrEqualTo(Long value) {
            addCriterion("creator_id >=", value, "creatorId");
            return (Criteria) this;
        }

        public Criteria andCreatorIdLessThan(Long value) {
            addCriterion("creator_id <", value, "creatorId");
            return (Criteria) this;
        }

        public Criteria andCreatorIdLessThanOrEqualTo(Long value) {
            addCriterion("creator_id <=", value, "creatorId");
            return (Criteria) this;
        }

        public Criteria andCreatorIdIn(List<Long> values) {
            addCriterion("creator_id in", values, "creatorId");
            return (Criteria) this;
        }

        public Criteria andCreatorIdNotIn(List<Long> values) {
            addCriterion("creator_id not in", values, "creatorId");
            return (Criteria) this;
        }

        public Criteria andCreatorIdBetween(Long value1, Long value2) {
            addCriterion("creator_id between", value1, value2, "creatorId");
            return (Criteria) this;
        }

        public Criteria andCreatorIdNotBetween(Long value1, Long value2) {
            addCriterion("creator_id not between", value1, value2, "creatorId");
            return (Criteria) this;
        }

        public Criteria andLastReadCatalogNameIsNull() {
            addCriterion("last_read_catalog_name is null");
            return (Criteria) this;
        }

        public Criteria andLastReadCatalogNameIsNotNull() {
            addCriterion("last_read_catalog_name is not null");
            return (Criteria) this;
        }

        public Criteria andLastReadCatalogNameEqualTo(String value) {
            addCriterion("last_read_catalog_name =", value, "lastReadCatalogName");
            return (Criteria) this;
        }

        public Criteria andLastReadCatalogNameNotEqualTo(String value) {
            addCriterion("last_read_catalog_name <>", value, "lastReadCatalogName");
            return (Criteria) this;
        }

        public Criteria andLastReadCatalogNameGreaterThan(String value) {
            addCriterion("last_read_catalog_name >", value, "lastReadCatalogName");
            return (Criteria) this;
        }

        public Criteria andLastReadCatalogNameGreaterThanOrEqualTo(String value) {
            addCriterion("last_read_catalog_name >=", value, "lastReadCatalogName");
            return (Criteria) this;
        }

        public Criteria andLastReadCatalogNameLessThan(String value) {
            addCriterion("last_read_catalog_name <", value, "lastReadCatalogName");
            return (Criteria) this;
        }

        public Criteria andLastReadCatalogNameLessThanOrEqualTo(String value) {
            addCriterion("last_read_catalog_name <=", value, "lastReadCatalogName");
            return (Criteria) this;
        }

        public Criteria andLastReadCatalogNameLike(String value) {
            addCriterion("last_read_catalog_name like", value, "lastReadCatalogName");
            return (Criteria) this;
        }

        public Criteria andLastReadCatalogNameNotLike(String value) {
            addCriterion("last_read_catalog_name not like", value, "lastReadCatalogName");
            return (Criteria) this;
        }

        public Criteria andLastReadCatalogNameIn(List<String> values) {
            addCriterion("last_read_catalog_name in", values, "lastReadCatalogName");
            return (Criteria) this;
        }

        public Criteria andLastReadCatalogNameNotIn(List<String> values) {
            addCriterion("last_read_catalog_name not in", values, "lastReadCatalogName");
            return (Criteria) this;
        }

        public Criteria andLastReadCatalogNameBetween(String value1, String value2) {
            addCriterion("last_read_catalog_name between", value1, value2, "lastReadCatalogName");
            return (Criteria) this;
        }

        public Criteria andLastReadCatalogNameNotBetween(String value1, String value2) {
            addCriterion("last_read_catalog_name not between", value1, value2, "lastReadCatalogName");
            return (Criteria) this;
        }

        public Criteria andLastReadCatalogLinkIsNull() {
            addCriterion("last_read_catalog_link is null");
            return (Criteria) this;
        }

        public Criteria andLastReadCatalogLinkIsNotNull() {
            addCriterion("last_read_catalog_link is not null");
            return (Criteria) this;
        }

        public Criteria andLastReadCatalogLinkEqualTo(String value) {
            addCriterion("last_read_catalog_link =", value, "lastReadCatalogLink");
            return (Criteria) this;
        }

        public Criteria andLastReadCatalogLinkNotEqualTo(String value) {
            addCriterion("last_read_catalog_link <>", value, "lastReadCatalogLink");
            return (Criteria) this;
        }

        public Criteria andLastReadCatalogLinkGreaterThan(String value) {
            addCriterion("last_read_catalog_link >", value, "lastReadCatalogLink");
            return (Criteria) this;
        }

        public Criteria andLastReadCatalogLinkGreaterThanOrEqualTo(String value) {
            addCriterion("last_read_catalog_link >=", value, "lastReadCatalogLink");
            return (Criteria) this;
        }

        public Criteria andLastReadCatalogLinkLessThan(String value) {
            addCriterion("last_read_catalog_link <", value, "lastReadCatalogLink");
            return (Criteria) this;
        }

        public Criteria andLastReadCatalogLinkLessThanOrEqualTo(String value) {
            addCriterion("last_read_catalog_link <=", value, "lastReadCatalogLink");
            return (Criteria) this;
        }

        public Criteria andLastReadCatalogLinkLike(String value) {
            addCriterion("last_read_catalog_link like", value, "lastReadCatalogLink");
            return (Criteria) this;
        }

        public Criteria andLastReadCatalogLinkNotLike(String value) {
            addCriterion("last_read_catalog_link not like", value, "lastReadCatalogLink");
            return (Criteria) this;
        }

        public Criteria andLastReadCatalogLinkIn(List<String> values) {
            addCriterion("last_read_catalog_link in", values, "lastReadCatalogLink");
            return (Criteria) this;
        }

        public Criteria andLastReadCatalogLinkNotIn(List<String> values) {
            addCriterion("last_read_catalog_link not in", values, "lastReadCatalogLink");
            return (Criteria) this;
        }

        public Criteria andLastReadCatalogLinkBetween(String value1, String value2) {
            addCriterion("last_read_catalog_link between", value1, value2, "lastReadCatalogLink");
            return (Criteria) this;
        }

        public Criteria andLastReadCatalogLinkNotBetween(String value1, String value2) {
            addCriterion("last_read_catalog_link not between", value1, value2, "lastReadCatalogLink");
            return (Criteria) this;
        }

        public Criteria andUpdatedIsNull() {
            addCriterion("updated is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedIsNotNull() {
            addCriterion("updated is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedEqualTo(Timestamp value) {
            addCriterion("updated =", value, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedNotEqualTo(Timestamp value) {
            addCriterion("updated <>", value, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedGreaterThan(Timestamp value) {
            addCriterion("updated >", value, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedGreaterThanOrEqualTo(Timestamp value) {
            addCriterion("updated >=", value, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedLessThan(Timestamp value) {
            addCriterion("updated <", value, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedLessThanOrEqualTo(Timestamp value) {
            addCriterion("updated <=", value, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedIn(List<Timestamp> values) {
            addCriterion("updated in", values, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedNotIn(List<Timestamp> values) {
            addCriterion("updated not in", values, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedBetween(Timestamp value1, Timestamp value2) {
            addCriterion("updated between", value1, value2, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedNotBetween(Timestamp value1, Timestamp value2) {
            addCriterion("updated not between", value1, value2, "updated");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table m_book_info
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table m_book_info
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}