package com.cn.lucky.morning.model.domain;

import java.sql.Timestamp;

public class BookSource {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_book_source.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_book_source.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_book_source.base_url
     *
     * @mbg.generated
     */
    private String baseUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_book_source.image_error
     *
     * @mbg.generated
     */
    private String imageError;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_book_source.search_url
     *
     * @mbg.generated
     */
    private String searchUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_book_source.search_result_selector
     *
     * @mbg.generated
     */
    private String searchResultSelector;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_book_source.result_item_book_name_selector
     *
     * @mbg.generated
     */
    private String resultItemBookNameSelector;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_book_source.result_item_book_url_selector
     *
     * @mbg.generated
     */
    private String resultItemBookUrlSelector;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_book_source.result_item_book_image_url_selector
     *
     * @mbg.generated
     */
    private String resultItemBookImageUrlSelector;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_book_source.result_item_book_des_selector
     *
     * @mbg.generated
     */
    private String resultItemBookDesSelector;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_book_source.result_item_book_author_selector
     *
     * @mbg.generated
     */
    private String resultItemBookAuthorSelector;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_book_source.result_item_book_type_selector
     *
     * @mbg.generated
     */
    private String resultItemBookTypeSelector;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_book_source.result_item_book_last_update_selector
     *
     * @mbg.generated
     */
    private String resultItemBookLastUpdateSelector;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_book_source.result_item_book_last_new_selector
     *
     * @mbg.generated
     */
    private String resultItemBookLastNewSelector;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_book_source.book_detail_book_name_selector
     *
     * @mbg.generated
     */
    private String bookDetailBookNameSelector;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_book_source.book_detail_book_author_selector
     *
     * @mbg.generated
     */
    private String bookDetailBookAuthorSelector;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_book_source.book_detail_book_last_update_selector
     *
     * @mbg.generated
     */
    private String bookDetailBookLastUpdateSelector;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_book_source.book_detail_book_last_new_selector
     *
     * @mbg.generated
     */
    private String bookDetailBookLastNewSelector;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_book_source.book_detail_book_des_selector
     *
     * @mbg.generated
     */
    private String bookDetailBookDesSelector;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_book_source.book_detail_book_image_url_selector
     *
     * @mbg.generated
     */
    private String bookDetailBookImageUrlSelector;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_book_source.book_detail_catalog_list_selector
     *
     * @mbg.generated
     */
    private String bookDetailCatalogListSelector;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_book_source.book_detail_catalog_item_name_selector
     *
     * @mbg.generated
     */
    private String bookDetailCatalogItemNameSelector;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_book_source.book_detail_catalog_item_link_selector
     *
     * @mbg.generated
     */
    private String bookDetailCatalogItemLinkSelector;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_book_source.book_content_catalog_name_selector
     *
     * @mbg.generated
     */
    private String bookContentCatalogNameSelector;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_book_source.book_content_name_selector
     *
     * @mbg.generated
     */
    private String bookContentNameSelector;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_book_source.book_content_selector
     *
     * @mbg.generated
     */
    private String bookContentSelector;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_book_source.content_regex
     *
     * @mbg.generated
     */
    private String contentRegex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_book_source.book_content_pre_catalog_selector
     *
     * @mbg.generated
     */
    private String bookContentPreCatalogSelector;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_book_source.book_content_catalog_list_selector
     *
     * @mbg.generated
     */
    private String bookContentCatalogListSelector;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_book_source.book_content_next_catalog_selector
     *
     * @mbg.generated
     */
    private String bookContentNextCatalogSelector;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_book_source.book_content_ads
     *
     * @mbg.generated
     */
    private String bookContentAds;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_book_source.created
     *
     * @mbg.generated
     */
    private Timestamp created;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_book_source.updated
     *
     * @mbg.generated
     */
    private Timestamp updated;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_book_source.id
     *
     * @return the value of m_book_source.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_book_source.id
     *
     * @param id the value for m_book_source.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_book_source.name
     *
     * @return the value of m_book_source.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_book_source.name
     *
     * @param name the value for m_book_source.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_book_source.base_url
     *
     * @return the value of m_book_source.base_url
     *
     * @mbg.generated
     */
    public String getBaseUrl() {
        return baseUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_book_source.base_url
     *
     * @param baseUrl the value for m_book_source.base_url
     *
     * @mbg.generated
     */
    public void setBaseUrl(String baseUrl) {
        this.baseUrl = baseUrl == null ? null : baseUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_book_source.image_error
     *
     * @return the value of m_book_source.image_error
     *
     * @mbg.generated
     */
    public String getImageError() {
        return imageError;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_book_source.image_error
     *
     * @param imageError the value for m_book_source.image_error
     *
     * @mbg.generated
     */
    public void setImageError(String imageError) {
        this.imageError = imageError == null ? null : imageError.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_book_source.search_url
     *
     * @return the value of m_book_source.search_url
     *
     * @mbg.generated
     */
    public String getSearchUrl() {
        return searchUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_book_source.search_url
     *
     * @param searchUrl the value for m_book_source.search_url
     *
     * @mbg.generated
     */
    public void setSearchUrl(String searchUrl) {
        this.searchUrl = searchUrl == null ? null : searchUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_book_source.search_result_selector
     *
     * @return the value of m_book_source.search_result_selector
     *
     * @mbg.generated
     */
    public String getSearchResultSelector() {
        return searchResultSelector;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_book_source.search_result_selector
     *
     * @param searchResultSelector the value for m_book_source.search_result_selector
     *
     * @mbg.generated
     */
    public void setSearchResultSelector(String searchResultSelector) {
        this.searchResultSelector = searchResultSelector == null ? null : searchResultSelector.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_book_source.result_item_book_name_selector
     *
     * @return the value of m_book_source.result_item_book_name_selector
     *
     * @mbg.generated
     */
    public String getResultItemBookNameSelector() {
        return resultItemBookNameSelector;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_book_source.result_item_book_name_selector
     *
     * @param resultItemBookNameSelector the value for m_book_source.result_item_book_name_selector
     *
     * @mbg.generated
     */
    public void setResultItemBookNameSelector(String resultItemBookNameSelector) {
        this.resultItemBookNameSelector = resultItemBookNameSelector == null ? null : resultItemBookNameSelector.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_book_source.result_item_book_url_selector
     *
     * @return the value of m_book_source.result_item_book_url_selector
     *
     * @mbg.generated
     */
    public String getResultItemBookUrlSelector() {
        return resultItemBookUrlSelector;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_book_source.result_item_book_url_selector
     *
     * @param resultItemBookUrlSelector the value for m_book_source.result_item_book_url_selector
     *
     * @mbg.generated
     */
    public void setResultItemBookUrlSelector(String resultItemBookUrlSelector) {
        this.resultItemBookUrlSelector = resultItemBookUrlSelector == null ? null : resultItemBookUrlSelector.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_book_source.result_item_book_image_url_selector
     *
     * @return the value of m_book_source.result_item_book_image_url_selector
     *
     * @mbg.generated
     */
    public String getResultItemBookImageUrlSelector() {
        return resultItemBookImageUrlSelector;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_book_source.result_item_book_image_url_selector
     *
     * @param resultItemBookImageUrlSelector the value for m_book_source.result_item_book_image_url_selector
     *
     * @mbg.generated
     */
    public void setResultItemBookImageUrlSelector(String resultItemBookImageUrlSelector) {
        this.resultItemBookImageUrlSelector = resultItemBookImageUrlSelector == null ? null : resultItemBookImageUrlSelector.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_book_source.result_item_book_des_selector
     *
     * @return the value of m_book_source.result_item_book_des_selector
     *
     * @mbg.generated
     */
    public String getResultItemBookDesSelector() {
        return resultItemBookDesSelector;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_book_source.result_item_book_des_selector
     *
     * @param resultItemBookDesSelector the value for m_book_source.result_item_book_des_selector
     *
     * @mbg.generated
     */
    public void setResultItemBookDesSelector(String resultItemBookDesSelector) {
        this.resultItemBookDesSelector = resultItemBookDesSelector == null ? null : resultItemBookDesSelector.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_book_source.result_item_book_author_selector
     *
     * @return the value of m_book_source.result_item_book_author_selector
     *
     * @mbg.generated
     */
    public String getResultItemBookAuthorSelector() {
        return resultItemBookAuthorSelector;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_book_source.result_item_book_author_selector
     *
     * @param resultItemBookAuthorSelector the value for m_book_source.result_item_book_author_selector
     *
     * @mbg.generated
     */
    public void setResultItemBookAuthorSelector(String resultItemBookAuthorSelector) {
        this.resultItemBookAuthorSelector = resultItemBookAuthorSelector == null ? null : resultItemBookAuthorSelector.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_book_source.result_item_book_type_selector
     *
     * @return the value of m_book_source.result_item_book_type_selector
     *
     * @mbg.generated
     */
    public String getResultItemBookTypeSelector() {
        return resultItemBookTypeSelector;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_book_source.result_item_book_type_selector
     *
     * @param resultItemBookTypeSelector the value for m_book_source.result_item_book_type_selector
     *
     * @mbg.generated
     */
    public void setResultItemBookTypeSelector(String resultItemBookTypeSelector) {
        this.resultItemBookTypeSelector = resultItemBookTypeSelector == null ? null : resultItemBookTypeSelector.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_book_source.result_item_book_last_update_selector
     *
     * @return the value of m_book_source.result_item_book_last_update_selector
     *
     * @mbg.generated
     */
    public String getResultItemBookLastUpdateSelector() {
        return resultItemBookLastUpdateSelector;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_book_source.result_item_book_last_update_selector
     *
     * @param resultItemBookLastUpdateSelector the value for m_book_source.result_item_book_last_update_selector
     *
     * @mbg.generated
     */
    public void setResultItemBookLastUpdateSelector(String resultItemBookLastUpdateSelector) {
        this.resultItemBookLastUpdateSelector = resultItemBookLastUpdateSelector == null ? null : resultItemBookLastUpdateSelector.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_book_source.result_item_book_last_new_selector
     *
     * @return the value of m_book_source.result_item_book_last_new_selector
     *
     * @mbg.generated
     */
    public String getResultItemBookLastNewSelector() {
        return resultItemBookLastNewSelector;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_book_source.result_item_book_last_new_selector
     *
     * @param resultItemBookLastNewSelector the value for m_book_source.result_item_book_last_new_selector
     *
     * @mbg.generated
     */
    public void setResultItemBookLastNewSelector(String resultItemBookLastNewSelector) {
        this.resultItemBookLastNewSelector = resultItemBookLastNewSelector == null ? null : resultItemBookLastNewSelector.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_book_source.book_detail_book_name_selector
     *
     * @return the value of m_book_source.book_detail_book_name_selector
     *
     * @mbg.generated
     */
    public String getBookDetailBookNameSelector() {
        return bookDetailBookNameSelector;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_book_source.book_detail_book_name_selector
     *
     * @param bookDetailBookNameSelector the value for m_book_source.book_detail_book_name_selector
     *
     * @mbg.generated
     */
    public void setBookDetailBookNameSelector(String bookDetailBookNameSelector) {
        this.bookDetailBookNameSelector = bookDetailBookNameSelector == null ? null : bookDetailBookNameSelector.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_book_source.book_detail_book_author_selector
     *
     * @return the value of m_book_source.book_detail_book_author_selector
     *
     * @mbg.generated
     */
    public String getBookDetailBookAuthorSelector() {
        return bookDetailBookAuthorSelector;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_book_source.book_detail_book_author_selector
     *
     * @param bookDetailBookAuthorSelector the value for m_book_source.book_detail_book_author_selector
     *
     * @mbg.generated
     */
    public void setBookDetailBookAuthorSelector(String bookDetailBookAuthorSelector) {
        this.bookDetailBookAuthorSelector = bookDetailBookAuthorSelector == null ? null : bookDetailBookAuthorSelector.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_book_source.book_detail_book_last_update_selector
     *
     * @return the value of m_book_source.book_detail_book_last_update_selector
     *
     * @mbg.generated
     */
    public String getBookDetailBookLastUpdateSelector() {
        return bookDetailBookLastUpdateSelector;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_book_source.book_detail_book_last_update_selector
     *
     * @param bookDetailBookLastUpdateSelector the value for m_book_source.book_detail_book_last_update_selector
     *
     * @mbg.generated
     */
    public void setBookDetailBookLastUpdateSelector(String bookDetailBookLastUpdateSelector) {
        this.bookDetailBookLastUpdateSelector = bookDetailBookLastUpdateSelector == null ? null : bookDetailBookLastUpdateSelector.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_book_source.book_detail_book_last_new_selector
     *
     * @return the value of m_book_source.book_detail_book_last_new_selector
     *
     * @mbg.generated
     */
    public String getBookDetailBookLastNewSelector() {
        return bookDetailBookLastNewSelector;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_book_source.book_detail_book_last_new_selector
     *
     * @param bookDetailBookLastNewSelector the value for m_book_source.book_detail_book_last_new_selector
     *
     * @mbg.generated
     */
    public void setBookDetailBookLastNewSelector(String bookDetailBookLastNewSelector) {
        this.bookDetailBookLastNewSelector = bookDetailBookLastNewSelector == null ? null : bookDetailBookLastNewSelector.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_book_source.book_detail_book_des_selector
     *
     * @return the value of m_book_source.book_detail_book_des_selector
     *
     * @mbg.generated
     */
    public String getBookDetailBookDesSelector() {
        return bookDetailBookDesSelector;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_book_source.book_detail_book_des_selector
     *
     * @param bookDetailBookDesSelector the value for m_book_source.book_detail_book_des_selector
     *
     * @mbg.generated
     */
    public void setBookDetailBookDesSelector(String bookDetailBookDesSelector) {
        this.bookDetailBookDesSelector = bookDetailBookDesSelector == null ? null : bookDetailBookDesSelector.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_book_source.book_detail_book_image_url_selector
     *
     * @return the value of m_book_source.book_detail_book_image_url_selector
     *
     * @mbg.generated
     */
    public String getBookDetailBookImageUrlSelector() {
        return bookDetailBookImageUrlSelector;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_book_source.book_detail_book_image_url_selector
     *
     * @param bookDetailBookImageUrlSelector the value for m_book_source.book_detail_book_image_url_selector
     *
     * @mbg.generated
     */
    public void setBookDetailBookImageUrlSelector(String bookDetailBookImageUrlSelector) {
        this.bookDetailBookImageUrlSelector = bookDetailBookImageUrlSelector == null ? null : bookDetailBookImageUrlSelector.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_book_source.book_detail_catalog_list_selector
     *
     * @return the value of m_book_source.book_detail_catalog_list_selector
     *
     * @mbg.generated
     */
    public String getBookDetailCatalogListSelector() {
        return bookDetailCatalogListSelector;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_book_source.book_detail_catalog_list_selector
     *
     * @param bookDetailCatalogListSelector the value for m_book_source.book_detail_catalog_list_selector
     *
     * @mbg.generated
     */
    public void setBookDetailCatalogListSelector(String bookDetailCatalogListSelector) {
        this.bookDetailCatalogListSelector = bookDetailCatalogListSelector == null ? null : bookDetailCatalogListSelector.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_book_source.book_detail_catalog_item_name_selector
     *
     * @return the value of m_book_source.book_detail_catalog_item_name_selector
     *
     * @mbg.generated
     */
    public String getBookDetailCatalogItemNameSelector() {
        return bookDetailCatalogItemNameSelector;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_book_source.book_detail_catalog_item_name_selector
     *
     * @param bookDetailCatalogItemNameSelector the value for m_book_source.book_detail_catalog_item_name_selector
     *
     * @mbg.generated
     */
    public void setBookDetailCatalogItemNameSelector(String bookDetailCatalogItemNameSelector) {
        this.bookDetailCatalogItemNameSelector = bookDetailCatalogItemNameSelector == null ? null : bookDetailCatalogItemNameSelector.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_book_source.book_detail_catalog_item_link_selector
     *
     * @return the value of m_book_source.book_detail_catalog_item_link_selector
     *
     * @mbg.generated
     */
    public String getBookDetailCatalogItemLinkSelector() {
        return bookDetailCatalogItemLinkSelector;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_book_source.book_detail_catalog_item_link_selector
     *
     * @param bookDetailCatalogItemLinkSelector the value for m_book_source.book_detail_catalog_item_link_selector
     *
     * @mbg.generated
     */
    public void setBookDetailCatalogItemLinkSelector(String bookDetailCatalogItemLinkSelector) {
        this.bookDetailCatalogItemLinkSelector = bookDetailCatalogItemLinkSelector == null ? null : bookDetailCatalogItemLinkSelector.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_book_source.book_content_catalog_name_selector
     *
     * @return the value of m_book_source.book_content_catalog_name_selector
     *
     * @mbg.generated
     */
    public String getBookContentCatalogNameSelector() {
        return bookContentCatalogNameSelector;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_book_source.book_content_catalog_name_selector
     *
     * @param bookContentCatalogNameSelector the value for m_book_source.book_content_catalog_name_selector
     *
     * @mbg.generated
     */
    public void setBookContentCatalogNameSelector(String bookContentCatalogNameSelector) {
        this.bookContentCatalogNameSelector = bookContentCatalogNameSelector == null ? null : bookContentCatalogNameSelector.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_book_source.book_content_name_selector
     *
     * @return the value of m_book_source.book_content_name_selector
     *
     * @mbg.generated
     */
    public String getBookContentNameSelector() {
        return bookContentNameSelector;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_book_source.book_content_name_selector
     *
     * @param bookContentNameSelector the value for m_book_source.book_content_name_selector
     *
     * @mbg.generated
     */
    public void setBookContentNameSelector(String bookContentNameSelector) {
        this.bookContentNameSelector = bookContentNameSelector == null ? null : bookContentNameSelector.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_book_source.book_content_selector
     *
     * @return the value of m_book_source.book_content_selector
     *
     * @mbg.generated
     */
    public String getBookContentSelector() {
        return bookContentSelector;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_book_source.book_content_selector
     *
     * @param bookContentSelector the value for m_book_source.book_content_selector
     *
     * @mbg.generated
     */
    public void setBookContentSelector(String bookContentSelector) {
        this.bookContentSelector = bookContentSelector == null ? null : bookContentSelector.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_book_source.content_regex
     *
     * @return the value of m_book_source.content_regex
     *
     * @mbg.generated
     */
    public String getContentRegex() {
        return contentRegex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_book_source.content_regex
     *
     * @param contentRegex the value for m_book_source.content_regex
     *
     * @mbg.generated
     */
    public void setContentRegex(String contentRegex) {
        this.contentRegex = contentRegex == null ? null : contentRegex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_book_source.book_content_pre_catalog_selector
     *
     * @return the value of m_book_source.book_content_pre_catalog_selector
     *
     * @mbg.generated
     */
    public String getBookContentPreCatalogSelector() {
        return bookContentPreCatalogSelector;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_book_source.book_content_pre_catalog_selector
     *
     * @param bookContentPreCatalogSelector the value for m_book_source.book_content_pre_catalog_selector
     *
     * @mbg.generated
     */
    public void setBookContentPreCatalogSelector(String bookContentPreCatalogSelector) {
        this.bookContentPreCatalogSelector = bookContentPreCatalogSelector == null ? null : bookContentPreCatalogSelector.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_book_source.book_content_catalog_list_selector
     *
     * @return the value of m_book_source.book_content_catalog_list_selector
     *
     * @mbg.generated
     */
    public String getBookContentCatalogListSelector() {
        return bookContentCatalogListSelector;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_book_source.book_content_catalog_list_selector
     *
     * @param bookContentCatalogListSelector the value for m_book_source.book_content_catalog_list_selector
     *
     * @mbg.generated
     */
    public void setBookContentCatalogListSelector(String bookContentCatalogListSelector) {
        this.bookContentCatalogListSelector = bookContentCatalogListSelector == null ? null : bookContentCatalogListSelector.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_book_source.book_content_next_catalog_selector
     *
     * @return the value of m_book_source.book_content_next_catalog_selector
     *
     * @mbg.generated
     */
    public String getBookContentNextCatalogSelector() {
        return bookContentNextCatalogSelector;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_book_source.book_content_next_catalog_selector
     *
     * @param bookContentNextCatalogSelector the value for m_book_source.book_content_next_catalog_selector
     *
     * @mbg.generated
     */
    public void setBookContentNextCatalogSelector(String bookContentNextCatalogSelector) {
        this.bookContentNextCatalogSelector = bookContentNextCatalogSelector == null ? null : bookContentNextCatalogSelector.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_book_source.book_content_ads
     *
     * @return the value of m_book_source.book_content_ads
     *
     * @mbg.generated
     */
    public String getBookContentAds() {
        return bookContentAds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_book_source.book_content_ads
     *
     * @param bookContentAds the value for m_book_source.book_content_ads
     *
     * @mbg.generated
     */
    public void setBookContentAds(String bookContentAds) {
        this.bookContentAds = bookContentAds == null ? null : bookContentAds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_book_source.created
     *
     * @return the value of m_book_source.created
     *
     * @mbg.generated
     */
    public Timestamp getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_book_source.created
     *
     * @param created the value for m_book_source.created
     *
     * @mbg.generated
     */
    public void setCreated(Timestamp created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_book_source.updated
     *
     * @return the value of m_book_source.updated
     *
     * @mbg.generated
     */
    public Timestamp getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_book_source.updated
     *
     * @param updated the value for m_book_source.updated
     *
     * @mbg.generated
     */
    public void setUpdated(Timestamp updated) {
        this.updated = updated;
    }
}