package com.cn.lucky.morning.model.domain;

import java.sql.Timestamp;

public class Donate {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_donate.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_donate.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_donate.nick_name
     *
     * @mbg.generated
     */
    private String nickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_donate.donate_money
     *
     * @mbg.generated
     */
    private String donateMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_donate.donate_source
     *
     * @mbg.generated
     */
    private String donateSource;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_donate.donate_time
     *
     * @mbg.generated
     */
    private Timestamp donateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_donate.id
     *
     * @return the value of m_donate.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_donate.id
     *
     * @param id the value for m_donate.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_donate.name
     *
     * @return the value of m_donate.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_donate.name
     *
     * @param name the value for m_donate.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_donate.nick_name
     *
     * @return the value of m_donate.nick_name
     *
     * @mbg.generated
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_donate.nick_name
     *
     * @param nickName the value for m_donate.nick_name
     *
     * @mbg.generated
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_donate.donate_money
     *
     * @return the value of m_donate.donate_money
     *
     * @mbg.generated
     */
    public String getDonateMoney() {
        return donateMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_donate.donate_money
     *
     * @param donateMoney the value for m_donate.donate_money
     *
     * @mbg.generated
     */
    public void setDonateMoney(String donateMoney) {
        this.donateMoney = donateMoney == null ? null : donateMoney.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_donate.donate_source
     *
     * @return the value of m_donate.donate_source
     *
     * @mbg.generated
     */
    public String getDonateSource() {
        return donateSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_donate.donate_source
     *
     * @param donateSource the value for m_donate.donate_source
     *
     * @mbg.generated
     */
    public void setDonateSource(String donateSource) {
        this.donateSource = donateSource == null ? null : donateSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_donate.donate_time
     *
     * @return the value of m_donate.donate_time
     *
     * @mbg.generated
     */
    public Timestamp getDonateTime() {
        return donateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_donate.donate_time
     *
     * @param donateTime the value for m_donate.donate_time
     *
     * @mbg.generated
     */
    public void setDonateTime(Timestamp donateTime) {
        this.donateTime = donateTime;
    }
}