package com.cn.lucky.morning.model.domain;

import java.sql.Timestamp;

public class LoginLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_login_log.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_login_log.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_login_log.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_login_log.login_ip
     *
     * @mbg.generated
     */
    private String loginIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_login_log.login_type
     *
     * @mbg.generated
     */
    private Integer loginType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_login_log.created
     *
     * @mbg.generated
     */
    private Timestamp created;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_login_log.id
     *
     * @return the value of m_login_log.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_login_log.id
     *
     * @param id the value for m_login_log.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_login_log.name
     *
     * @return the value of m_login_log.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_login_log.name
     *
     * @param name the value for m_login_log.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_login_log.user_id
     *
     * @return the value of m_login_log.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_login_log.user_id
     *
     * @param userId the value for m_login_log.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_login_log.login_ip
     *
     * @return the value of m_login_log.login_ip
     *
     * @mbg.generated
     */
    public String getLoginIp() {
        return loginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_login_log.login_ip
     *
     * @param loginIp the value for m_login_log.login_ip
     *
     * @mbg.generated
     */
    public void setLoginIp(String loginIp) {
        this.loginIp = loginIp == null ? null : loginIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_login_log.login_type
     *
     * @return the value of m_login_log.login_type
     *
     * @mbg.generated
     */
    public Integer getLoginType() {
        return loginType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_login_log.login_type
     *
     * @param loginType the value for m_login_log.login_type
     *
     * @mbg.generated
     */
    public void setLoginType(Integer loginType) {
        this.loginType = loginType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_login_log.created
     *
     * @return the value of m_login_log.created
     *
     * @mbg.generated
     */
    public Timestamp getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_login_log.created
     *
     * @param created the value for m_login_log.created
     *
     * @mbg.generated
     */
    public void setCreated(Timestamp created) {
        this.created = created;
    }
}