package com.cn.lucky.morning.model.domain;

public class SystemSetting {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_system_setting.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_system_setting.sitename
     *
     * @mbg.generated
     */
    private String sitename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_system_setting.domain
     *
     * @mbg.generated
     */
    private String domain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_system_setting.admin_index_name
     *
     * @mbg.generated
     */
    private String adminIndexName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_system_setting.meta_keywords
     *
     * @mbg.generated
     */
    private String metaKeywords;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_system_setting.meta_description
     *
     * @mbg.generated
     */
    private String metaDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_system_setting.copyright_info
     *
     * @mbg.generated
     */
    private String copyrightInfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_system_setting.id
     *
     * @return the value of m_system_setting.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_system_setting.id
     *
     * @param id the value for m_system_setting.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_system_setting.sitename
     *
     * @return the value of m_system_setting.sitename
     *
     * @mbg.generated
     */
    public String getSitename() {
        return sitename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_system_setting.sitename
     *
     * @param sitename the value for m_system_setting.sitename
     *
     * @mbg.generated
     */
    public void setSitename(String sitename) {
        this.sitename = sitename == null ? null : sitename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_system_setting.domain
     *
     * @return the value of m_system_setting.domain
     *
     * @mbg.generated
     */
    public String getDomain() {
        return domain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_system_setting.domain
     *
     * @param domain the value for m_system_setting.domain
     *
     * @mbg.generated
     */
    public void setDomain(String domain) {
        this.domain = domain == null ? null : domain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_system_setting.admin_index_name
     *
     * @return the value of m_system_setting.admin_index_name
     *
     * @mbg.generated
     */
    public String getAdminIndexName() {
        return adminIndexName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_system_setting.admin_index_name
     *
     * @param adminIndexName the value for m_system_setting.admin_index_name
     *
     * @mbg.generated
     */
    public void setAdminIndexName(String adminIndexName) {
        this.adminIndexName = adminIndexName == null ? null : adminIndexName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_system_setting.meta_keywords
     *
     * @return the value of m_system_setting.meta_keywords
     *
     * @mbg.generated
     */
    public String getMetaKeywords() {
        return metaKeywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_system_setting.meta_keywords
     *
     * @param metaKeywords the value for m_system_setting.meta_keywords
     *
     * @mbg.generated
     */
    public void setMetaKeywords(String metaKeywords) {
        this.metaKeywords = metaKeywords == null ? null : metaKeywords.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_system_setting.meta_description
     *
     * @return the value of m_system_setting.meta_description
     *
     * @mbg.generated
     */
    public String getMetaDescription() {
        return metaDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_system_setting.meta_description
     *
     * @param metaDescription the value for m_system_setting.meta_description
     *
     * @mbg.generated
     */
    public void setMetaDescription(String metaDescription) {
        this.metaDescription = metaDescription == null ? null : metaDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_system_setting.copyright_info
     *
     * @return the value of m_system_setting.copyright_info
     *
     * @mbg.generated
     */
    public String getCopyrightInfo() {
        return copyrightInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_system_setting.copyright_info
     *
     * @param copyrightInfo the value for m_system_setting.copyright_info
     *
     * @mbg.generated
     */
    public void setCopyrightInfo(String copyrightInfo) {
        this.copyrightInfo = copyrightInfo == null ? null : copyrightInfo.trim();
    }
}