package com.cn.lucky.morning.model.domain;

import java.sql.Timestamp;

public class UpdateLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_update_log.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_update_log.created
     *
     * @mbg.generated
     */
    private Timestamp created;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_update_log.updated
     *
     * @mbg.generated
     */
    private Timestamp updated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_update_log.update_des
     *
     * @mbg.generated
     */
    private String updateDes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_update_log.id
     *
     * @return the value of m_update_log.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_update_log.id
     *
     * @param id the value for m_update_log.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_update_log.created
     *
     * @return the value of m_update_log.created
     *
     * @mbg.generated
     */
    public Timestamp getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_update_log.created
     *
     * @param created the value for m_update_log.created
     *
     * @mbg.generated
     */
    public void setCreated(Timestamp created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_update_log.updated
     *
     * @return the value of m_update_log.updated
     *
     * @mbg.generated
     */
    public Timestamp getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_update_log.updated
     *
     * @param updated the value for m_update_log.updated
     *
     * @mbg.generated
     */
    public void setUpdated(Timestamp updated) {
        this.updated = updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_update_log.update_des
     *
     * @return the value of m_update_log.update_des
     *
     * @mbg.generated
     */
    public String getUpdateDes() {
        return updateDes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_update_log.update_des
     *
     * @param updateDes the value for m_update_log.update_des
     *
     * @mbg.generated
     */
    public void setUpdateDes(String updateDes) {
        this.updateDes = updateDes == null ? null : updateDes.trim();
    }
}